export const users = [
  {
    id: 1,
    name: "Alice Johnson",
    age: 25,
    email: "alice.johnson@example.com",
    type: "admin",
  },
  {
    id: 2,
    name: "Bob Smith",
    age: 30,
    email: "bob.smith@example.com",
    type: "common",
  },
  {
    id: 3,
    name: "Charlie Brown",
    age: 40,
    email: "charlie.brown@example.com",
    type: "admin",
  },
  {
    id: 4,
    name: "Diana Prince",
    age: 30,
    email: "diana.prince@example.com",
    type: "common",
  },
  {
    id: 5,
    name: "Evan Wright",
    age: 35,
    email: "evan.wright@example.com",
    type: "admin",
  },
  {
    id: 6,
    name: "Fiona Green",
    age: 29,
    email: "fiona.green@example.com",
    type: "common",
  },
  {
    id: 7,
    name: "George Hill",
    age: 50,
    email: "george.hill@example.com",
    type: "admin",
  },
  {
    id: 8,
    name: "Hannah Scott",
    age: 19,
    email: "hannah.scott@example.com",
    type: "common",
  },
  {
    id: 9,
    name: "Ian Clarke",
    age: 28,
    email: "ian.clarke@example.com",
    type: "admin",
  },
  {
    id: 10,
    name: "Julia Adams",
    age: 45,
    email: "julia.adams@example.com",
    type: "common",
  },
];
